### ISSUE TITLE
RuntimeError: Directory '~/paios/frontend/dist' does not exist

### ISSUE THREAD

**Issue by samj** [pAI-OS/paios#41]
Freshly cloned paios repo doesn't contain a built frontend (i.e., frontent/dist directory), so it fails to start:

```shell
% python -m paios
INFO:     Creating the app.
INFO:     Initializing database.
INFO:     Context impl SQLiteImpl.
INFO:     Will assume non-transactional DDL.
INFO:     Running upgrade  -> 56a640fb45b2, Config model
INFO:     Running upgrade 56a640fb45b2 -> 75aaaf2cd1a2, Added resource table
INFO:     Running upgrade 75aaaf2cd1a2 -> 0d66a93c6c1f, Added user table
INFO:     Running upgrade 0d66a93c6c1f -> cb6e97a5186c, added asset table
INFO:     Running upgrade cb6e97a5186c -> f5235ab5e888, added persona table
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "~/Development/paios/__main__.py", line 37, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "~/Development/paios/app.py", line 7, in create_app
    add_frontend_app(app)
  File "~/Development/paios/app.py", line 16, in add_frontend_app
    view_func=StaticFiles(directory=static_dir, html=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Development/paios/.venv/lib/python3.12/site-packages/starlette/staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '~/Development/paios/frontend/dist' does not exist
```

**Comment by samj** [comment]
Note that how I got here is by running `./scripts/setup_environment.py` without node being installed (which I do with `brew install npm` on macOS). If node isn't found the script prints a message but doesn't fail. Maybe it should.
